This library is for numerical python. You can do efficient manipulation of large datasets. Seamless integration with other data handling and AI libraries. Under the hood it is implemented in C and fortran for speed.

In [5]:
try:
    import numpy as np
except ImportError:
    print("NumPy not found installing")
    %pip install numpy

print(np.__version__)

2.4.6


# NumPy array
NumPy array expects the data to be of one type only, it is optimized for speed. Python directly does not have an array, it has to use NumPy.

In [16]:
# Create an array, takes in a list
arr = np.array([1, 2, 3, 4])
print(f"Array : {arr}")
print(arr.dtype)

# Create an array with a range of values
arr_range = np.arange(10)
print(f"Array with range : {arr_range}")

# Create an array of zeros, shape should be given as a tuple
arr_zeros = np.zeros((3,3)) # 3X3 array, with 0's
print(f"Array of zeros : {arr_zeros}")

# Create an array of 1's of type int
arr_ones = np.ones((2,2), dtype=int)
print(f"Array of ones : {arr_ones}")

# Reshaping an array, it should be of the same size
arr_reshaped = arr_range.reshape((2,5))
print(f"Reshaped array : {arr_reshaped}")

# Getting the shape of an array
print(f"Shape of an array : {arr_reshaped.shape}")

# Basic arithematic operations
arr_sum = arr + 2
print(f"Array after addition : {arr_sum}")
arr_mul = arr * 3
print(f"Array after multiplication : {arr_mul}")

# Element wise operations
arr1 = np.array([1, 2, 3, 4])
arr2 = np.array([5, 6, 7, 8])
arr_add = arr1 + arr2
print(f"Element-wise addition : {arr_add}")
arr_mul = arr1 * arr2
print(f"Element-wise multiplication : {arr_mul}")

Array : [1 2 3 4]
int64
Array with range : [0 1 2 3 4 5 6 7 8 9]
Array of zeros : [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
Array of ones : [[1 1]
 [1 1]]
Reshaped array : [[0 1 2 3 4]
 [5 6 7 8 9]]
Shape of an array : (2, 5)
Array after addition : [3 4 5 6]
Array after multiplication : [ 3  6  9 12]
Element-wise addition : [ 6  8 10 12]
Element-wise multiplication : [ 5 12 21 32]


In [ ]:
# Mathematical operations, many many mathematical operations in NumPy
# below are a few
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])
print(arr.mean())
print(np.median(arr))
print(np.std(arr))

4.5
4.5
2.29128784747792


In [23]:
# Filter the arrays
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])
print(arr > 4)
arr_fil = arr[arr > 4] # arr > 4 is called the boolean mask
print(arr_fil)
print((arr > 4) & (arr < 7))

[False False False False  True  True  True  True]
[5 6 7 8]
[False False False False  True  True False False]
